# Generated by Django 5.0.3 on 2024-03-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebOwner', '0004_remove_tbl_boatdetails_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_boatdetails',
        ),
    ]
