# Generated by Django 5.0.3 on 2024-03-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebOwner', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_boatdetails',
        ),
    ]
