# Generated by Django 5.0.4 on 2024-04-11 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0003_tbl_boattype'),
        ('WebWorkShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic_name', models.CharField(max_length=50)),
                ('mechanic_contact', models.CharField(max_length=50)),
                ('mechanic_email', models.CharField(max_length=50)),
                ('mechanic_password', models.CharField(max_length=50)),
                ('mechanic_photo', models.FileField(upload_to='Assets/MechDocs/')),
                ('mechanic_proof', models.FileField(upload_to='Assets/MechDocs/')),
                ('mechanic_status', models.IntegerField(default='0')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_place')),
            ],
        ),
    ]
