# Generated by Django 5.0.4 on 2024-04-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebWorkShop', '0002_tbl_mechanic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_mechanic',
        ),
    ]
