# Generated by Django 5.0.3 on 2024-03-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WebAdmin', '0003_tbl_boattype'),
        ('WebGuest', '0004_alter_tbl_shop_shop_photo_alter_tbl_shop_shop_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_details', models.CharField(max_length=50)),
                ('product_rate', models.CharField(max_length=50)),
                ('product_photo', models.FileField(upload_to='Assets/ProductPhoto/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_brand')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebGuest.tbl_shop')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_subcategory')),
            ],
        ),
    ]
