# Generated by Django 5.0.3 on 2024-03-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0003_tbl_boattype'),
        ('WebGuest', '0004_alter_tbl_shop_shop_photo_alter_tbl_shop_shop_proof_and_more'),
        ('WebShop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_user',
            new_name='tbl_product',
        ),
    ]
