# Generated by Django 5.0.3 on 2024-04-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebShop', '0002_rename_tbl_user_tbl_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='product_stock',
            field=models.IntegerField(default=0),
        ),
    ]
