# Generated by Django 5.0.3 on 2024-04-11 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebShop', '0003_tbl_product_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_productstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_qty', models.IntegerField(default=0)),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebShop.tbl_product')),
            ],
        ),
    ]
