# Generated by Django 5.0.3 on 2024-03-30 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0001_initial'),
        ('WebGuest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_boatowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_gender', models.CharField(max_length=50)),
                ('owner_contact', models.CharField(max_length=50)),
                ('owner_email', models.CharField(max_length=50)),
                ('owner_address', models.CharField(max_length=500)),
                ('owner_about', models.CharField(max_length=500)),
                ('owner_password', models.CharField(max_length=50)),
                ('owner_photo', models.FileField(upload_to='Assets/OwnerPhoto/')),
                ('owner_proof', models.FileField(upload_to='Assets/OwnerProof/')),
                ('owner_status', models.IntegerField(default='0')),
                ('owner_doj', models.DateField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_place')),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_artist',
        ),
    ]
