# Generated by Django 5.0.3 on 2024-03-30 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0001_initial'),
        ('WebGuest', '0002_tbl_boatowner_delete_tbl_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_contact', models.CharField(max_length=50)),
                ('shop_email', models.CharField(max_length=50)),
                ('shop_address', models.CharField(max_length=500)),
                ('shop_about', models.CharField(max_length=500)),
                ('shop_password', models.CharField(max_length=50)),
                ('shop_photo', models.FileField(upload_to='Assets/OwnerPhoto/')),
                ('shop_proof', models.FileField(upload_to='Assets/OwnerProof/')),
                ('shop_status', models.IntegerField(default='0')),
                ('shop_doj', models.DateField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=50)),
                ('workshop_contact', models.CharField(max_length=50)),
                ('workshop_email', models.CharField(max_length=50)),
                ('workshop_address', models.CharField(max_length=500)),
                ('workshop_about', models.CharField(max_length=500)),
                ('workshop_password', models.CharField(max_length=50)),
                ('workshop_photo', models.FileField(upload_to='Assets/OwnerPhoto/')),
                ('workshop_proof', models.FileField(upload_to='Assets/OwnerProof/')),
                ('workshop_status', models.IntegerField(default='0')),
                ('workshop_doj', models.DateField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_place')),
            ],
        ),
    ]
