# Generated by Django 5.0.3 on 2024-03-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebUser', '0003_tbl_requestboat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_requestboat',
        ),
    ]
