# Generated by Django 5.0.3 on 2024-03-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebUser', '0005_tbl_requestboat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_requestboat',
            old_name='boatid',
            new_name='boat',
        ),
    ]
