# Generated by Django 5.0.3 on 2024-04-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUser', '0007_tbl_booking_tbl_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_amount',
            field=models.IntegerField(default=0),
        ),
    ]
