# Generated by Django 5.0.3 on 2024-04-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUser', '0008_alter_tbl_booking_booking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_amount',
            field=models.CharField(max_length=30),
        ),
    ]
