# Generated by Django 5.0.3 on 2024-04-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebUser', '0009_alter_tbl_booking_booking_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='product',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
