# Generated by Django 5.0.3 on 2024-04-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebUser', '0011_tbl_booking_tbl_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='product',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
