# Generated by Django 5.0.4 on 2024-04-12 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebUser', '0013_tbl_booking_tbl_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_requestservice',
        ),
    ]
