# Generated by Django 5.0.4 on 2024-04-12 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUser', '0015_tbl_requestservice'),
        ('WebWorkShop', '0004_tbl_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_requestservice',
            name='mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebWorkShop.tbl_mechanic'),
        ),
    ]
